// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnuzwxhzbyilkhsortwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJudXp3eGh6YnlpbGtoc29ydHdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3ODU5ODUsImV4cCI6MjA2MzM2MTk4NX0.majv0l_MReTuy_0N1WIVKxAERC2yrIovJk7omNHFZKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);